### ISSUE TITLE
Large number of iron golems

### ISSUE THREAD

**Issue by TheFaser** [foss-mc/Patina#4] opened 2021-08-11 10:01 UTC
I am using the latest build of Patina and am faced with a huge golem spawn issue

![2021-08-11_14 56 30](https://user-images.githubusercontent.com/69783345/129010117-79b145b3-4f26-4e18-b492-9bd1a89dde09.png)

This is not one case and is repeated many times. All you need is a village of two inhabitants and time

**Comment by toinouH** [comment] 2021-08-13 12:04
@foss-mc Your opinion on this ?

**Comment by toinouH** [comment] 2021-08-16 13:14
Hello @TheFaser could you provide your plugin list and your datapacks since we were not able to reproduce this ?
Thank you for your help :D

**Comment by TheFaser** [comment] 2021-08-16 19:37
![Screenshot_21](https://user-images.githubusercontent.com/69783345/129619701-c8264904-80db-45d4-8c99-9d12e716e904.png)
I had such a number of golems only 2 times, this has not happened in the last days. I think it will be very difficult to repeat again

**Comment by foss-mc** [comment] 2021-08-17 03:25
It was fixed in airplane

**Closed as completed by foss-mc** 2021-08-17 03:25 UTC
Labels: bug, upstream:airplane
