### ISSUE TITLE
Please solve the problem :)

### ISSUE THREAD

**Issue by ohnenny** [foss-mc/Patina#11] opened 2022-01-03 17:25 UTC
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 03.01.22 20:07
Description: Exception in server tick loop

java.lang.IllegalArgumentException: Unexpected exception java.lang.reflect.InvocationTargetException while attempting to construct a new instance of org.bukkit.plugin.java.JavaPluginLoader
	at org.bukkit.plugin.SimplePluginManager.registerInterface(SimplePluginManager.java:95)
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:384)
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:290)
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074)
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.bukkit.plugin.SimplePluginManager.registerInterface(SimplePluginManager.java:89)
	... 5 more
Caused by: java.lang.NullPointerException
	at org.bukkit.plugin.java.LibraryLoader.<init>(LibraryLoader.java:59)
	at org.bukkit.plugin.java.JavaPluginLoader.<init>(JavaPluginLoader.java:73)
	... 10 more

A detailed walkthrough of the error, its code path and all known details is as follows:

**Comment by toinouH** [comment] 2022-02-08 14:58
This is a duplicate of #10.
Thank you for the report anyway :)

**Closed as completed by toinouH** 2022-02-08 14:58 UTC
Labels: duplicate
